---
title: "Task 1 analysis"
---

```{r}
#load libraries
library(tidyverse)
library(readr)
library(here)
library(janitor)
```

```{r}
#read in dataset
decathlon_data <- read.csv(here("clean_data/decathlon_clean.csv")) #, check.names = FALSE)
decathlon_data <- decathlon_data[,-1]
view(decathlon_data)
head(decathlon_data)
```


```{r}
#Question 1
# Who had the longest long jump seen in the data?
decathlon_data %>% 
  select(name, long_jump) %>% 
  slice_max(long_jump, n = 1)  
```


```{r}
#Question 2
#What was the average 100m time in each competition?
decathlon_data %>% 
  group_by(competition) %>% 
  summarise(avg_100m_time = mean(X100_metre_race, na.rm = TRUE))

```


```{r}
#Question 3
#Who had the highest total points across both competitions?
decathlon_data %>% 
 group_by(name) %>% 
   summarise (total_points = sum(points)) %>% 
  slice_max(total_points, n = 1)
```


```{r}
#Question 4
#What was the shot-put scores for the top three competitors in each competition?
decathlon_data %>% 
  select(name, shot_put, competition) %>% 
  group_by(competition) %>% 
  slice_max(shot_put, n = 3)
```


```{r}
#Question 5
#What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?
less_than_50secs <- decathlon_data %>% 
  filter(X400_metre_race < 50.00) %>% 
  summarise("average points running 400m in less than 50 seconds" = mean(points, na.rm = TRUE))
less_than_50secs

more_than_50secs <- decathlon_data %>% 
  filter(X400_metre_race > 50.00) %>% 
summarise("average points running 400m in more than 50 seconds" = mean(points, na.rm = TRUE))
more_than_50secs
```


```{r}
#Visual - Total Score by competitor by competition

ggplot(
  decathlon_data,
  aes(x = name, y = points, fill = competition)) +
  geom_col(position = "dodge") +
  labs(
    x = "Athlete name",
    y = "Total points",
    fill = "Competition",
    title = "Total Score by competitor and competition")+
  coord_flip()



ggplot(
  decathlon_data,
  aes(x = factor(name), y = points, fill = competition)) +
  geom_col() + 
  labs(
   x = "Athlete name",
    y = "Total points",
    fill = "Competition",
    title = "Total Score by competitor and competition")+
  coord_flip()
    
```

